version: '2'

services:
  python:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/python:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - 8000:8000
    volumes:
      - .:/app
